# endpoint: /api/bill_items


###
GET http://localhost:3000/api/bill_items


###
POST  http://localhost:3000/api/bill_items
Content-Type: application/json

{
    "quantity": 3,
    "id_book":"65eedc621396293d05a47286"
}


###
GET http://localhost:3000/api/bill_items/65eee3fb4dae2a1cdd35e378


###
DELETE  http://localhost:3000/api/bill_items/65eee3fb4dae2a1cdd35e378


###
PATCH  http://localhost:3000/api/bill_items/65eee3fb4dae2a1cdd35e378
Content-Type: application/json

{
    "quantity": 10
}
