# endpoint: /api/bills


###
GET http://localhost:3000/api/bills


###
POST  http://localhost:3000/api/bills
Content-Type: application/json

{
    "detail":["65ee5875c607e3d4d882bbd3","65eedc621396293d05a47286"],
    "id_user":"65ee5875c607e3d4d882bbd3",
    "id_address": "65ee5875c607e3d4d882bbd3"
}


###
GET http://localhost:3000/api/bills/65eee2a0a769865369fc1d8d


###
DELETE  http://localhost:3000/api/bills/65eee2a0a769865369fc1d8d


###
PATCH  http://localhost:3000/api/bills/65eee2a0a769865369fc1d8d
Content-Type: application/json

{
    "id_address": "65eedc621396293d05a47286"
}
