# endpoint: /api/books


###
GET http://localhost:3000/api/books


###
POST  http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "One Piece",
    "id_category": "65eed4e720a285c93ea38b9d"
}


###
GET http://localhost:3000/api/books/65eed58a13476e92277389d7


###
DELETE  http://localhost:3000/api/books/65eed58a13476e92277389d7


###
PATCH  http://localhost:3000/api/books/65eed58a13476e92277389d7
Content-Type: application/json

{
    "name": "updated"
}
