# books

### getAll
GET http://localhost:3000/api/books


### add
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "one piece",
    "id_category":"65d6d98281ba668fb7f9c9c7"
}


### get
GET http://localhost:3000/api/books/65d7460c4e154cfa301d98ee


### remove
DELETE  http://localhost:3000/api/books/65d7460c4e154cfa301d98ee


### set
PATCH  http://localhost:3000/api/books/65d7460b4e154cfa301d98ec
Content-Type: application/json

{
    "name": "dragon ball z"
}