# endpoint: /api/carts


###
GET http://localhost:3000/api/carts


###
POST  http://localhost:3000/api/carts
Content-Type: application/json

{
    "quantity": 10,
    "id_book": "65eedc621396293d05a47286"
}


###
GET http://localhost:3000/api/carts/65eedcd73031f0d62faf0dce


###
DELETE  http://localhost:3000/api/carts/65eedcd73031f0d62faf0dce


###
PATCH  http://localhost:3000/api/carts/65eedcd73031f0d62faf0dce
Content-Type: application/json

{
    "quantity": 3
}
