# endpoint: /api/evaluates


###
GET http://localhost:3000/api/evaluates


###
POST  http://localhost:3000/api/evaluates
Content-Type: application/json

{
    "star": 4.5,
    "id_user": "65ee5875c607e3d4d882bbd3"
}


###
GET http://localhost:3000/api/evaluates/65eeda152eee0d2c6bc4c1d5


###
DELETE  http://localhost:3000/api/evaluates/65eeda152eee0d2c6bc4c1d5


###
PATCH  http://localhost:3000/api/evaluates/65eeda152eee0d2c6bc4c1d5
Content-Type: application/json

{
   "star": 5
}
