# evaluates

### getAll
GET http://localhost:3000/api/evaluates


### add
POST http://localhost:3000/api/evaluates
Content-Type: application/json

{
    "number": 5,
    "id_user":"65d6d98281ba668fb7f9c9c7"
}


### get
GET http://localhost:3000/api/evaluates/65d747104e154cfa301d990e


### remove
DELETE  http://localhost:3000/api/evaluates/65d747114e154cfa301d9910


### set
PATCH  http://localhost:3000/api/evaluates/65d747104e154cfa301d990e
Content-Type: application/json

{
    "comment":"thanks your feedback." 
}