# variations

### getAll
GET http://localhost:3000/api/variations


### add
POST http://localhost:3000/api/variations
Content-Type: application/json

{
    "quality": "new"
}


### get
GET http://localhost:3000/api/variations/65d747724e154cfa301d9922


### remove
DELETE  http://localhost:3000/api/variations/65d745544e154cfa301d98df


### set
PATCH  http://localhost:3000/api/variations/65d747724e154cfa301d9922
Content-Type: application/json

{
    "quality": "likenew",
    "language":"en"
}